2024-03-16 13:46:37,208 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-03-16 13:47:59,980 django.request WARNING  Not Found: /
2024-03-16 13:48:00,078 django.request WARNING  Not Found: /favicon.ico
2024-03-16 13:48:03,426 django.request ERROR    Internal Server Error: /cityservice/admin/login/
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python310\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Python310\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Python310\lib\site-packages\django\contrib\admin\sites.py", line 422, in login
    **self.each_context(request),
  File "C:\Python310\lib\site-packages\django\contrib\admin\sites.py", line 337, in each_context
    "available_apps": self.get_app_list(request),
  File "C:\Python310\lib\site-packages\django\contrib\admin\sites.py", line 536, in get_app_list
    app_dict = self._build_app_dict(request, app_label)
  File "C:\Python310\lib\site-packages\django\contrib\admin\sites.py", line 478, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "C:\Python310\lib\site-packages\django\contrib\admin\options.py", line 611, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "C:\Python310\lib\site-packages\django\contrib\auth\models.py", line 331, in has_module_perms
    return _user_has_module_perms(self, app_label)
  File "C:\Python310\lib\site-packages\django\contrib\auth\models.py", line 235, in _user_has_module_perms
    if backend.has_module_perms(user, app_label):
  File "C:\Python310\lib\site-packages\django\contrib\auth\backends.py", line 121, in has_module_perms
    for perm in self.get_all_permissions(user_obj)
  File "C:\Python310\lib\site-packages\django\contrib\auth\backends.py", line 109, in get_all_permissions
    user_obj._perm_cache = super().get_all_permissions(user_obj)
  File "C:\Python310\lib\site-packages\django\contrib\auth\backends.py", line 27, in get_all_permissions
    *self.get_user_permissions(user_obj, obj=obj),
  File "C:\Python310\lib\site-packages\django\contrib\auth\backends.py", line 96, in get_user_permissions
    return self._get_permissions(user_obj, obj, "user")
  File "C:\Python310\lib\site-packages\django\contrib\auth\backends.py", line 84, in _get_permissions
    perms = getattr(self, "_get_%s_permissions" % from_name)(user_obj)
  File "C:\Python310\lib\site-packages\django\contrib\auth\backends.py", line 63, in _get_user_permissions
    return user_obj.user_permissions.all()
AttributeError: 'NoneType' object has no attribute 'all'
2024-03-16 13:48:04,327 django.request WARNING  Not Found: /cityservice
2024-03-16 13:48:04,546 django.request WARNING  Not Found: /cityservice
2024-03-16 13:48:22,756 django.utils.autoreload INFO     C:\Users\ёрий\Desktop\BD_Proekt\cityservice\cityservice\settings.py changed, reloading.
2024-03-16 14:35:21,152 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-03-16 14:37:01,923 django.request WARNING  Not Found: /favicon.ico
2024-03-16 14:38:01,308 django.request WARNING  Not Found: /favicon.ico
2024-03-16 14:39:28,671 django.request WARNING  Not Found: /favicon.ico
